### ISSUE TITLE
Add support for IQ dumps

### ISSUE THREAD

**Issue by cshields** [satnogs/gr-satnogs#103]
Have an opt-in option for saving IQ data at the same time as the demod / decode data, for those who have enough storage and CPU power to do so.

**Comment by surligas** [comment]
Yes it will be extremely useful. As far as I can see, this can be a sink block taking a parameter if it is enabled or not. If not, it just drops the samples. Otherwise, it could convert them to interleaved shorts by properly scaling the input samples and store them to a file. This could reduce the file size by 50%.

A more efficient solution would be to perform custom connections based on the parameter in the python scripts, but of course this will break the auto-generation feature of GRC.

**Comment by surligas** [comment]
@ctriant offered to implement this!

**Comment by ctriant** [comment]
Seems like I could help with that :)

**Comment by GVardakis** [comment]
Added IQ Sink block to all flowgraphs in #107

**Comment by ctriant** [comment]
This issue is fixed after @GVardakis '  PR and should be closed :)
